name: Acquire Unity Activation File (.alf)

on:
  workflow_dispatch:

jobs:
  activation:
    name: Generate .alf file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate manual activation file
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: iOS
          unityVersion: 6000.4.9f1
          customParameters: -createManualActivationFile

      - name: Upload activation file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity_v6.alf
          path: manual-activation-file.alf
